//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TQBits.Context
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Candidate
    {
        public int Id { get; set; }
        [Required(ErrorMessage = "Required")]
        public string Name { get; set; }
        [Required(ErrorMessage = "Required")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd/MM-yyyy}", ApplyFormatInEditMode = true)]
        public System.DateTime DateOfBirth { get; set; }
        [Required(ErrorMessage = "Required")]
        public bool Married { get; set; }
        [Required(ErrorMessage = "Required")]
        public string Phone { get; set; }
        [Required(ErrorMessage = "Required")]
        public decimal Salary { get; set; }
    }
}
